### ISSUE TITLE
组件管理模块文档

### ISSUE THREAD

**Issue by bjwswang** [kubebb/website#1]
组建管理文档结构：
```
- 组件管理Core
   - 介绍 Intro
   -  概念Concepts
   -  快速开始
   -  用户指南
      -  仓库和组件
      -  订阅和部署
```

**Comment by bjwswang** [comment]
@Abirdcfly @0xff-dev  补充下对应模块的用户指南，细化到详细的CRD spec的配置

**Comment by 0xff-dev** [comment]
<img width="1019" alt="image" src="https://github.com/kubebb/website/assets/20641704/0d4e40ad-4625-4389-ba4a-4ccdd3ac3962">
使用这种格式？

**Comment by bjwswang** [comment]
@0xff-dev @Abirdcfly 

我们可以参考下kubernetes官网对Pod等资源的介绍、使用、
https://kubernetes.io/docs/concepts/workloads/pods/

这个方面的文档都可以放到：
http://kubebb.k8s.com.cn/docs/core/concepts


如果concepts这里介绍的足够完整，用户指南这部分可以先放着，暂时不加东西。

**Comment by bjwswang** [comment]
> <img alt="image" width="1019" src="https:user-images.githubusercontent.com/20641704/246784646-0d4e40ad-4625-4389-ba4a-4ccdd3ac3962.png"> Use this format?

除了介绍规范之外，这里还需要详细解释一下仓库:

- 对仓库源的要求
- 仓库详细的过滤规则
- watcher的原理和详细的组件处理流程

与pod类似，存储库的概念介绍可以分为几个层次:

```
- concept
  - Repsitory :  基本概念
       - Source
       - Filter
       - Watcher
```
